spring.application.name=api-recepcao
# ===============================
# CONFIGURAÇÃO DO SERVIDOR
# ===============================
server.port=8080

# ===============================
# BANCO DE DADOS H2 (EM MEMÓRIA)
# ===============================
spring.datasource.url=jdbc:h2:mem:recepcaodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# ddl-auto=update diz ao Spring para criar as tabelas automaticamente baseado nas nossas classes @Entity
spring.jpa.hibernate.ddl-auto=update
# show-sql e format_sql mostram no console os comandos de banco de dados acontecendo por trás dos panos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# PAINEL VISUAL DO BANCO H2
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console